### ISSUE TITLE
Use network instead of host mode

### ISSUE THREAD

**Issue by tstrohmeier** [vuestorefront/vue-storefront#4399]
## What is the motivation for adding / enhancing this feature?
As mentioned in #3299 there is an issue with the current docker-compose configuration on OSX. I suggest to use external networks instead of the `network_mode: host`.

## What are the acceptance criteria 
* [ ] `network_mode: host` is removed fro the docker-compose.yml
* [ ] the api project network is added as external network to the docker-compose.yml

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
My suggested modifications:

```
version: '2.0'
services:
  app:
    # image: divante/vue-storefront:latest
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    env_file: docker/vue-storefront/default.env
    environment:
      VS_ENV: dev
# REMOVE this line
#    network_mode: host
    volumes:
      - './babel.config.js:/var/www/babel.config.js'
      - './config:/var/www/config'
      - './core:/var/www/core'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './.eslintignore:/var/www/.eslintignore'
      - './.eslintrc.js:/var/www/.eslintrc.js'
      - './lerna.json:/var/www/lerna.json'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './tsconfig-build.json:/var/www/tsconfig-build.json'
      - './shims.d.ts:/var/www/shims.d.ts'
      - './package.json:/var/www/package.json'
      - './src:/var/www/src'
      - './var:/var/www/var'
      - './packages:/var/www/packages'
    tmpfs:
      - /var/www/dist
# ADD this line
    networks:
      - vue-storefront-api_default
    ports:
      - '3000:3000'

# ADD this lines
networks:
  vue-storefront-api_default:
    external: true
```
